// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oeNXnGQEdksZJsVWiuOvnuEif81ky04',
    appId: '1:281869670516:web:83b2cc0306df28370cd921',
    messagingSenderId: '281869670516',
    projectId: 'example-recipe-app-a9a76',
    authDomain: 'example-recipe-app-a9a76.firebaseapp.com',
    storageBucket: 'example-recipe-app-a9a76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCoCaN-eBrk3_WcT3H-2VK7wVvBbbO4ek',
    appId: '1:281869670516:android:272903e051ab2af30cd921',
    messagingSenderId: '281869670516',
    projectId: 'example-recipe-app-a9a76',
    storageBucket: 'example-recipe-app-a9a76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_m0Ohjb5Gjnb-13hw0JiDBpalbF_N8rI',
    appId: '1:336003961732:ios:a9d1a65f8ee8016e0503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_m0Ohjb5Gjnb-13hw0JiDBpalbF_N8rI',
    appId: '1:336003961732:ios:a9d1a65f8ee8016e0503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7oeNXnGQEdksZJsVWiuOvnuEif81ky04',
    appId: '1:281869670516:web:64ad5c2d361f3ae10cd921',
    messagingSenderId: '281869670516',
    projectId: 'example-recipe-app-a9a76',
    authDomain: 'example-recipe-app-a9a76.firebaseapp.com',
    storageBucket: 'example-recipe-app-a9a76.firebasestorage.app',
  );

}